name: Hugo broken link check

on:
  pull_request:
    branches:
      - main

jobs:
  broken-link-check:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Check for broken Links
      uses: marojor/hugo-broken-link-checker@v1.0.5
      with:
        skip-file: skip-rules-for-links-check.txt
