name: Hugo Link Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Hugo Link Check
        uses: marccampbell/hugo-linkcheck-action@v0.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUGO_FINAL_URL: "https://mke4-docs.com"
