name: PR

on:
  pull_request:
    types: ["opened", "reopened", "synchronize", "ready_for_review"]
    branches: ["main"]
    paths:
      - "content/**" # all files otherwise excludes wont work

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-pr-check
          fail_on_error: true
          config_file: .github/.linkspector.yml
